enum CommandErrors {
  EXCEPTION = 'EXCEPTION',
  COOLDOWN = 'COOLDOWN',
  INVALID_ARGUMENTS = 'INVALID ARGUMENTS',
  MISSING_PERMISSIONS = 'MISSING PERMISSIONS',
  MISSING_ROLES = 'MISSING ROLES',
  COMMAND_DISABLED = 'COMMAND DISABLED',
  COMMAND_NOT_FOUND = 'COMMANT NOT FOUND'
}

export default CommandErrors
